0 398~OLFrom: Kapo  [ Nedela 1st Jul 2007 at 11:10pm ] 
~FG~OLBol si povyseny na level: ~RS~OLUSADLIK.

~OLFrom: Kapo  [ Nedela 1st Jul 2007 at 11:10pm ] 
~FG~OLBol si povyseny na level: ~RS~OLKLERIK.

~OLFrom: Kapo  [ Nedela 1st Jul 2007 at 11:10pm ] 
~FG~OLBol si povyseny na level: ~RS~OLKUZELNIK.

~OLFrom: Kapo  [ Nedela 1st Jul 2007 at 11:10pm ] 
~FG~OLBol si povyseny na level: ~RS~OLDRUID.

