version       0.3
password      NUwat6yABwVgI
promote_date  on Streda 4th Jul 2007 at 02:40pm
times         1591013450 1311012 318 1183324294
levels        6 6 0 0 0
general       -1 0 0 0 1 0 0 41
user_set      0 0 0 23 1 0 0 0 0 0 1 0 #UNSET 0
user_ignores  0 0 0 0 0 0 0 0
purging       1 1594469450
last_site     localhost hlavna_ulica
mail_verify   kapo@kubuntu.sk
description   to tu riesi
in_phrase     vosiel
out_phrase    odisiel
email         #UNSET
homepage      #UNSET
recap_name    Mutant
games         0 0 0 0 6 10 8268 3000
sklonovanie   Mutant Mutanta Mutantovi Mutanta Mutantovi Mutantom
