2007-07-01 19:54:59: Bol vytvoreny.
2007-07-01 20:03:08: Kapo ho ~FGpovysil~RS na level USADLIK.
2007-07-01 20:03:15: Kapo ho ~FGpovysil~RS na level KLERIK.
2007-07-01 20:03:55: Kapo ho ~FGpovysil~RS na level KUZELNIK.
2007-07-01 20:15:14: Kapo ho ~FGpovysil~RS na level DRUID.
2007-07-01 23:08:21: Bol vytvoreny.
2007-07-01 23:09:15: Made a request for an account.
2007-07-01 23:09:15: Used email address "kapo@kubuntu.sk" in the request.
2007-07-01 23:10:12: Kapo ho ~FGpovysil~RS na level USADLIK.
2007-07-01 23:10:15: Kapo ho ~FGpovysil~RS na level KLERIK.
2007-07-01 23:10:23: Kapo ho ~FGpovysil~RS na level KUZELNIK.
2007-07-01 23:10:28: Kapo ho ~FGpovysil~RS na level DRUID.
2007-07-04 14:30:48: Kapo ho ~FGpovysil~RS na level ANJEL.
2007-07-04 14:39:59: Was ~FRarrested~RS by Kapo (at level ~OLARCHANJEL~RS).
2007-07-04 14:40:17: Was ~FGunarrested~RS by Kapo.
2020-05-30 20:06:44: ~FRKilled~RS by Kapo.
